In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\mahi2\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mahi2\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mahi2\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\mahi2\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\mahi2\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!pip install --upgrade pip

Requirement already satisfied: pip in c:\users\mahi2\appdata\local\programs\python\python313\lib\site-packages (24.3.1)

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FD88AC0EC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FD88A76350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FD88A765D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FD88A76850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FD88A76AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pip/

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
#import pandas
import pandas as pd

In [5]:
pd.__version__

'3.0.2'

In [6]:
### 1 create Dataframe

In [7]:
df=pd.DataFrame([11,22,33],columns=['col_name'])
print(df)

   col_name
0        11
1        22
2        33

In [12]:
print(type(df))

<class 'pandas.DataFrame'>

In [10]:
data={
   'name':['madhav','lalita','rishabh'],
    'age':[16,17,18],
    'salary':[1000,2000,3000]

}

In [11]:
df=pd.DataFrame(data)
print(df)

      name  age  salary
0   madhav   16    1000
1   lalita   17    2000
2  rishabh   18    3000

In [15]:
print(type(df))

<class 'pandas.DataFrame'>

In [16]:
###2 basic Dataframe understanding

In [17]:
df.head(2) ##it gives by default only top rows

     name  age  salary
0  madhav   16    1000
1  lalita   17    2000

In [18]:
df.tail(2) #it gives by default only last rows

      name  age  salary
1   lalita   17    2000
2  rishabh   18    3000

In [19]:
df.shape

(3, 3)

In [20]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

In [24]:
df.rename(columns={'salary':'Monthly_salary'})

      name  age  Monthly_salary
0   madhav   16            1000
1   lalita   17            2000
2  rishabh   18            3000

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [26]:
df.describe() #basicaly it give high level statisticaly summary

        age  salary
count   3.0     3.0
mean   17.0  2000.0
std     1.0  1000.0
min    16.0  1000.0
25%    16.5  1500.0
50%    17.0  2000.0
75%    17.5  2500.0
max    18.0  3000.0

In [27]:
###3 save and load data from csv

In [32]:
df.to_csv('test_data.csv')  #it is save in pandas folder  #export dataframe

In [30]:
load_df=pd.read_csv('test_data.csv') #import data frame 
load_df

   Unnamed: 0     name  age  salary
0           0   madhav   16    1000
1           1   lalita   17    2000
2           2  rishabh   18    3000

In [33]:
###4 rows and columns selection

In [34]:
#select column 
df[['name']]

      name
0   madhav
1   lalita
2  rishabh

In [35]:
#selecting  multile  columns 
df[['name','age']]

      name  age
0   madhav   16
1   lalita   17
2  rishabh   18

In [38]:
#selet row 
#loc=index name based/label based index
df.loc[df.name=='madhav']
df.loc[(df.name=='madhav')&(df.salary>=500)]

     name  age  salary
0  madhav   16    1000

In [39]:
#iloc =index value based 
df.iloc[0]

name      madhav
age           16
salary      1000
Name: 0, dtype: object

In [42]:
df.iloc[1]
df.loc[0:2] #its containt last index values

      name  age  salary
0   madhav   16    1000
1   lalita   17    2000
2  rishabh   18    3000

In [41]:
#for selecting multiple 
df.iloc[0:2] #its imp for data analysis 
#it doesnt contain last index value [start:stop:step]

     name  age  salary
0  madhav   16    1000
1  lalita   17    2000

In [1]:
###5 filtering DataFrame

In [12]:
df

      name  age  salary
0   madhav   16    1000
1   lalita   17    2000
2  rishabh   18    3000

In [13]:
df['age']>15

0    True
1    True
2    True
Name: age, dtype: bool

In [14]:
df[df['age']>17] #for sorting particular value

      name  age  salary
2  rishabh   18    3000

In [16]:
df[(df['age']>=16) &(df['salary']>=1000)]

      name  age  salary
0   madhav   16    1000
1   lalita   17    2000
2  rishabh   18    3000

In [17]:
df.where(df['age']>=16)

      name  age  salary
0   madhav   16    1000
1   lalita   17    2000
2  rishabh   18    3000

In [18]:
###6 rows and column-operation(Add,update ,delete)

In [19]:
df

      name  age  salary
0   madhav   16    1000
1   lalita   17    2000
2  rishabh   18    3000

In [22]:
#add new column 
df['Team']=['ceo','HR','CTO']
df

      name  age  salary Team
0   madhav   16    1000  ceo
1   lalita   17    2000   HR
2  rishabh   18    3000  CTO

In [24]:
#bonus column 
df['bonus']=df['salary']*0.2
df

      name  age  salary Team  bonus
0   madhav   16    1000  ceo  200.0
1   lalita   17    2000   HR  400.0
2  rishabh   18    3000  CTO  600.0

In [25]:
 ##ading new row 
df.loc[len(df)]=['abc',21,3200,'it',200]
df

      name  age  salary Team  bonus
0   madhav   16    1000  ceo  200.0
1   lalita   17    2000   HR  400.0
2  rishabh   18    3000  CTO  600.0
3      abc   21    3200   it  200.0

In [26]:
len(df)

4

In [28]:
#update value 
df.loc[0,'salary']=4000
df

      name  age  salary Team  bonus
0   madhav   16    4000  ceo  200.0
1   lalita   17    2000   HR  400.0
2  rishabh   18    3000  CTO  600.0
3      abc   21    3200   it  200.0

In [30]:
#update value using column values 
df.loc[df.name=='madhav','salary']=9000
df

      name  age  salary Team  bonus
0   madhav   16    9000  ceo  200.0
1   lalita   17    2000   HR  400.0
2  rishabh   18    3000  CTO  600.0
3      abc   21    3200   it  200.0

In [36]:
#delete  values-row column values 
df.drop(df[df.name=='abc'].index) #drop row ,axis=0

In [37]:
df[df.name=='abc']

Empty DataFrame
Columns: [name, age, salary, Team, bonus]
Index: []

In [38]:
df.drop('bonus',axis=1)

      name  age  salary Team
0   madhav   16    9000  ceo
1   lalita   17    2000   HR
2  rishabh   18    3000  CTO

In [ ]:
#drop row on the basis of index number

In [45]:
df.drop(1,axis=0)

      name  age  salary Team  bonus
0   madhav   16    9000  ceo  200.0
2  rishabh   18    3000  CTO  600.0

In [46]:
#sort values 
df.sort_values('salary')  #ascending order

      name  age  salary Team  bonus
1   lalita   17    2000   HR  400.0
2  rishabh   18    3000  CTO  600.0
0   madhav   16    9000  ceo  200.0

In [47]:
df.sort_values('salary',ascending=False) #dscending values

      name  age  salary Team  bonus
0   madhav   16    9000  ceo  200.0
2  rishabh   18    3000  CTO  600.0
1   lalita   17    2000   HR  400.0

In [48]:
###7working with date values

In [50]:
df['DOJ']=['2024-06-06','2024-08-09','2024-03-05']
df

      name  age  salary Team  bonus         DOJ
0   madhav   16    9000  ceo  200.0  2024-06-06
1   lalita   17    2000   HR  400.0  2024-08-09
2  rishabh   18    3000  CTO  600.0  2024-03-05

In [53]:
df['DOJ']=pd.to_datetime(df['DOJ'])
df

      name  age  salary Team  bonus        DOJ
0   madhav   16    9000  ceo  200.0 2024-06-06
1   lalita   17    2000   HR  400.0 2024-08-09
2  rishabh   18    3000  CTO  600.0 2024-03-05

In [54]:
df['DOJ'].dtype

dtype('<M8[us]')

In [55]:
df1=df

In [58]:
df1['DOJ2']=['02-03-2024','15-02-2024','23-02-2024']
df1

      name  age  salary Team  bonus        DOJ        DOJ2
0   madhav   16    9000  ceo  200.0 2024-06-06  02-03-2024
1   lalita   17    2000   HR  400.0 2024-08-09  15-02-2024
2  rishabh   18    3000  CTO  600.0 2024-03-05  23-02-2024

In [59]:
#sorting date 
df1['DOJ2']=pd.to_datetime(df1['DOJ2'],format='%d-%m-%Y') ##very very imp in data  analysis 
df

      name  age  salary Team  bonus        DOJ       DOJ2
0   madhav   16    9000  ceo  200.0 2024-06-06 2024-03-02
1   lalita   17    2000   HR  400.0 2024-08-09 2024-02-15
2  rishabh   18    3000  CTO  600.0 2024-03-05 2024-02-23

In [60]:
df1['DOJ2'].dtype #its converting in to datatime

dtype('<M8[us]')

In [61]:
df=df.drop('DOJ2',axis=1)
df

      name  age  salary Team  bonus        DOJ
0   madhav   16    9000  ceo  200.0 2024-06-06
1   lalita   17    2000   HR  400.0 2024-08-09
2  rishabh   18    3000  CTO  600.0 2024-03-05

In [64]:
df['DOJ'].dt.year #sorting year wise 
df['DOJ'].dt.month  #sorting month wise 
df['DOJ'].dt.day #sortiing day wise  
df['DOJ'].dt.day_name()

0    Thursday
1      Friday
2     Tuesday
Name: DOJ, dtype: str

In [65]:
df['month']=df['DOJ'].dt.month

In [66]:
df

      name  age  salary Team  bonus        DOJ  month
0   madhav   16    9000  ceo  200.0 2024-06-06      6
1   lalita   17    2000   HR  400.0 2024-08-09      8
2  rishabh   18    3000  CTO  600.0 2024-03-05      3

In [68]:
df['DOJ']+pd.Timedelta(days=90)
df

      name  age  salary Team  bonus        DOJ  month
0   madhav   16    9000  ceo  200.0 2024-06-06      6
1   lalita   17    2000   HR  400.0 2024-08-09      8
2  rishabh   18    3000  CTO  600.0 2024-03-05      3

In [69]:
### 8 handling missing values

In [70]:
df

      name  age  salary Team  bonus        DOJ  month
0   madhav   16    9000  ceo  200.0 2024-06-06      6
1   lalita   17    2000   HR  400.0 2024-08-09      8
2  rishabh   18    3000  CTO  600.0 2024-03-05      3

In [71]:
df.isnull()

    name    age  salary   Team  bonus    DOJ  month
0  False  False   False  False  False  False  False
1  False  False   False  False  False  False  False
2  False  False   False  False  False  False  False

In [73]:
import numpy as np

In [74]:
df.loc[df.name=='lalita','salary']=np.nan

      name  age  salary Team  bonus        DOJ  month
0   madhav   16  9000.0  ceo  200.0 2024-06-06      6
1   lalita   17     NaN   HR  400.0 2024-08-09      8
2  rishabh   18  3000.0  CTO  600.0 2024-03-05      3

In [75]:
df.isnull()

    name    age  salary   Team  bonus    DOJ  month
0  False  False   False  False  False  False  False
1  False  False    True  False  False  False  False
2  False  False   False  False  False  False  False

In [78]:
df.isnull().sum()  #this will be usefull in large dataset

name      0
age       0
salary    1
Team      0
bonus     0
DOJ       0
month     0
dtype: int64

In [87]:
#to remove missing values 
df.fillna(0) #then this data is useful for further analysis

      name  age  salary Team  bonus        DOJ  month
0   madhav   16  9000.0  ceo  200.0 2024-06-06      6
1   lalita   17     0.0   HR  400.0 2024-08-09      8
2  rishabh   18  3000.0  CTO  600.0 2024-03-05      3

In [84]:
### 9 Aggregation and group by

In [88]:
df=pd.DataFrame(data)
print(df)

      name  age  salary
0   madhav   16    1000
1   lalita   17    2000
2  rishabh   18    3000

In [90]:
df['name'].value_counts()

name
madhav     1
lalita     1
rishabh    1
Name: count, dtype: int64

In [93]:
df.groupby('name')['salary'].sum()

name
lalita     2000
madhav     1000
rishabh    3000
Name: salary, dtype: int64

In [94]:
df.groupby('name')['salary'].mean() #for taking average  #agregation base on group by

name
lalita     2000.0
madhav     1000.0
rishabh    3000.0
Name: salary, dtype: float64

In [95]:
df['DOJ']=['2024-06-06','2024-08-09','2024-03-05']
df

      name  age  salary         DOJ
0   madhav   16    1000  2024-06-06
1   lalita   17    2000  2024-08-09
2  rishabh   18    3000  2024-03-05

In [100]:
###10 concatenate and merge DataFrame (JOINS)
df1=pd.DataFrame({'ID':[1,2,3],'name':['A','B','C']})
df1

   ID name
0   1    A
1   2    B
2   3    C

In [101]:
df2=pd.DataFrame({'ID':[1,2,3,4],'scores':[88,96,77,79]})
df2

   ID  scores
0   1      88
1   2      96
2   3      77
3   4      79

In [102]:
pd.concat([df1,df2],axis=0) #vertical joinn /row level/top on top

   ID name  scores
0   1    A     NaN
1   2    B     NaN
2   3    C     NaN
0   1  NaN    88.0
1   2  NaN    96.0
2   3  NaN    77.0
3   4  NaN    79.0

In [103]:
pd.concat([df1,df2],axis=1) #horizontal/column level

    ID name  ID  scores
0  1.0    A   1      88
1  2.0    B   2      96
2  3.0    C   3      77
3  NaN  NaN   4      79

In [104]:
#merge =join 

pd.merge(df1,df2,how='inner',on='ID')

   ID name  scores
0   1    A      88
1   2    B      96
2   3    C      77

In [105]:
pd.merge(df1,df2,how='inner',left_on='ID',right_on='ID')

   ID name  scores
0   1    A      88
1   2    B      96
2   3    C      77